[package]
name = "format_docx"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64 = "0.22.1"
format_shared = { path = "../format_shared" }
viewer_core = { path = "../viewer_core" }

[dev-dependencies]
viewer_ffi = { path = "../viewer_ffi" }
tempfile = "3.15.0"
zip = { version = "2.4.2", default-features = false, features = ["deflate"] }
